//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace b8c217db_ede2_4676_857c_1ec01327e1b3 {
    
    
    public partial class ViewSwitcher {
    }
}
