'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Entreprise
    Public Property Id As Integer
    Public Property NomEnt As String
    Public Property Respon As String
    Public Property Qualité As String
    Public Property Contact As String
    Public Property [Date] As Date

End Class
